name: Checkout

on:
  workflow_dispatch:
  
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出程式碼
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 設定 Docker Compose
      - name: Set up Docker
        run: |
          docker build -t app_image_formation_fast:app_image_formation_fast .
          docker run -it --rm -p 8501:8501 app_image_formation_fast:app_image_formation_fast

      - name: sleep
        run: sleep 600
